"use server"

import { sendEmail } from "@/lib/email/send"
import { createClient } from "@/lib/supabase/server"

interface SendReportEmailParams {
  reportName: string
  recipients: string[]
  downloadUrl: string
  format: string
}

export async function sendReportEmail(data: SendReportEmailParams) {
  const supabase = await createClient()
  const {
    data: { user },
  } = await supabase.auth.getUser()

  if (!user) {
    return { success: false, error: "Unauthorized" }
  }

  try {
    const emailHtml = `
      <html>
        <body style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
          <div style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); padding: 30px; text-align: center;">
            <h1 style="color: white; margin: 0;">Taxu Reports</h1>
          </div>
          <div style="padding: 30px; background: white;">
            <h2>Your ${data.reportName} is Ready</h2>
            <p>Your requested report has been generated and is ready for download.</p>
            <div style="margin: 20px 0; padding: 15px; background: #f3f4f6; border-radius: 8px;">
              <p style="margin: 0;"><strong>Report:</strong> ${data.reportName}</p>
              <p style="margin: 8px 0 0 0;"><strong>Format:</strong> ${data.format}</p>
            </div>
            <a href="${data.downloadUrl}" style="display: inline-block; background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 12px 24px; text-decoration: none; border-radius: 6px; font-weight: bold;">
              Download Report
            </a>
            <p style="margin-top: 30px; font-size: 14px; color: #6b7280;">
              This report was automatically generated by Taxu. If you have any questions, please contact support.
            </p>
          </div>
          <div style="padding: 20px; text-align: center; background: #f9fafb; color: #6b7280; font-size: 12px;">
            <p>© 2025 Taxu. All rights reserved.</p>
          </div>
        </body>
      </html>
    `

    for (const recipient of data.recipients) {
      await sendEmail({
        to: recipient,
        subject: `Your ${data.reportName} Report is Ready`,
        html: emailHtml,
        userId: user.id,
        emailType: "report_delivery",
      })
    }

    console.log("[v0] Sent report emails to:", data.recipients.length, "recipients")

    return {
      success: true,
      message: `Report sent to ${data.recipients.length} recipient(s)`,
    }
  } catch (error) {
    console.error("[v0] Error sending report email:", error)
    return {
      success: false,
      error: error instanceof Error ? error.message : "Failed to send report email",
    }
  }
}
